apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luxdent-smv-pp-ua
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maksimshemet/dentistry.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: luxdent

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

  healthChecks:
    - name: certificate-health
      kind: Certificate
      apiVersion: cert-manager.io/v1
      health: Healthy

    
