apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxdent
  labels:
    app: luxdent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luxdent
  template:
    metadata:
      labels:
        app: luxdent
    spec:
      containers:
        - name: luxdent
          image: shemetmaksim/dentistry:1.0.0
          ports:
            - containerPort: 80