apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxdent
  labels:
    app: luxdent-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luxdent-app
    spec:
      containers:
        - name: luxdent
          image: shemetmaksim/dentistry:0.0.1
          ports:
            - containerPort: 80