apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luxdent-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - luxdent.smv.pp.ua
      secretName: luxdent-cert
  rules:
    - host: luxdent.smv.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: luxdent-svc
                port:
                  number: 80